version: '3'

services:
  openldap:
    build: ./openldap
    image: autentia/openldap
    ports:
      - 389:389
    environment:
      - SLAPD_DOMAIN=autentia.com
      - SLAPD_PASSWORD=adminadmin
      - SLAPD_CONFIG_PASSWORD=config
      - SLAPD_ADDITIONAL_SCHEMAS=ppolicy
      - SLAPD_ADDITIONAL_MODULES=ppolicy
    container_name: autentia-ldap
